# Generated by Django 3.2.6 on 2022-03-16 17:59

from django.db import migrations, models
import shop.utils.upload


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220316_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.ImageField(blank=True, upload_to=shop.utils.upload.upload_function, verbose_name='Фото'),
        ),
    ]
