# Generated by Django 3.2.6 on 2021-12-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartgoods',
            options={'verbose_name': 'Продукт корзины', 'verbose_name_plural': 'Продукты корзины'},
        ),
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartgoods',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
