# Generated by Django 3.2.6 on 2022-03-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_order_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[('unpaid', 'Неоплачен'), ('pay_inprogress', 'Платеж в обработке'), ('paid', 'Оплачен')], default='unpaid', max_length=100, verbose_name='Статус платежа'),
        ),
    ]
