# Generated by Django 3.2.6 on 2022-03-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ отдан'), ('canceled', 'Заказ отменен')], default='new', max_length=100, verbose_name='Статус платежа'),
        ),
    ]
