# Generated by Django 3.2.6 on 2022-03-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_order_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[('Неоплачен', 'Неоплачен'), ('Платеж в обработке', 'Платеж в обработке'), ('Оплачен', 'Оплачен')], default='Неоплачен', max_length=100, verbose_name='Статус платежа'),
        ),
    ]
