# Generated by Django 3.2.6 on 2022-03-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Отчество (если есть)'),
        ),
    ]
