# Generated by Django 3.2.6 on 2022-04-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20220413_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=255, verbose_name='Область/Край'),
        ),
    ]
