# Generated by Django 3.2.6 on 2022-04-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ отдан'), ('canceled', 'Заказ отменен')], default='Почта РФ', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
