# Generated by Django 3.2.6 on 2022-04-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_order_buying_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('pochta', 'Почта РФ'), ('SDEK', 'СДЭК')], default='pochta', max_length=100, verbose_name='Тип заказа'),
        ),
    ]
