# Generated by Django 3.1.4 on 2022-05-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20220505_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название товара'),
        ),
    ]
