# Generated by Django 3.1.4 on 2022-05-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_goods_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Meta-description'),
        ),
    ]
