# Generated by Django 3.1.4 on 2022-05-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_cart_total_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_count',
        ),
    ]
